apiVersion: v1
kind: Secret
metadata:
  name: lf-sync-cws
type: Opaque
stringData:
  TRELLIS_SESSION_KEY_SEED: replace-with-a-service-session-key-seed
  CWS_API: https://replace-with-cws-api-root/
  CWS_REPO: replace-with-cws-repository
  CWS_SERVER: replace-with-cws-server
  CWS_USER: replace-with-cws-user
  CWS_PASSWORD: replace-with-cws-password
---
apiVersion: v1
kind: Secret
metadata:
  name: lf-sync-database
type: Opaque
stringData:
  DATABASE_URL: postgresql://replace-with-database-connection-url
